### ISSUE TITLE
File not found 

### ISSUE THREAD

**Issue by Totobal5** [NunoDasNeves/slp-to-mp4#19]
Traceback (most recent call last):
  File "e:\slp-to-mp4-master\slp2mp4\slp-to-mp4.py", line 217, in <module>
    main()
  File "e:\slp-to-mp4-master\slp2mp4\slp-to-mp4.py", line 213, in main
    record_file_slp(slp_file, outfile)
  File "e:\slp-to-mp4-master\slp2mp4\slp-to-mp4.py", line 79, in record_file_slp
    video_file, audio_file = dolphin_runner.run(slp_file, num_frames)
  File "e:\slp-to-mp4-master\slp2mp4\dolphinrunner.py", line 224, in run
    self.prep_dolphin_settings()
  File "e:\slp-to-mp4-master\slp2mp4\dolphinrunner.py", line 161, in prep_dolphin_settings
    with open(gale01_ini_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'e:\\slp-to-mp4-master\\slp2mp4\\User-31a785c4-57f1-42dc-9953-4528f0520d14\\GameSettings\\GALE01.ini'

**Comment by davisdude** [comment]
It's very difficult to help with how little information you've given. Which version of Slippi are you using? Which version of `slp-to-mp4`? What OS are you using (seems to be Windows)?

Also, I'll eventually make a PR to fix this at some point, but I may have fixed the issue [on my branch](https://github.com/davisdude/slp2mp4) already.

**Comment by Totobal5** [comment]
Sorry for the litle information, i am using windows 10, i am using the master branch of this repo. 
My config file is the following 

{
  "melee_iso": "C:/Program Files/Slippy/SSBMv102.iso",
  "dolphin_dir": "C:/Users/toot/AppData/Roaming/Slippi Launcher/playback/",
  "ffmpeg": "C:/ffmpeg-2022-09-15-git-3f0fac9303-full_build/bin/ffmpeg.exe",
  "resolution": "720p",
  "widescreen": true,
  "bitrateKbps": 16000,
  "parallel_games": "recommended",
  "remove_short": true,
  "combine": true
}

and i am in the last version of Slippy (Ishiiruka) 2.5.2

**Comment by davisdude** [comment]
Ah, I see. Seems like they're not using the `GALE01.ini` anymore for some reason (but will still leave it if it was there before, which is how I never noticed it I guess). I can fix this on my branch (and attempt a PR here), but it might be better to switch to my fork of it, since this project hasn't seen any active maintenance in a while as far as I can tell.

**Comment by davisdude** [comment]
Here's [my fix](https://github.com/davisdude/slp2mp4/commit/2d361ae6afe58e456b67cb603714fbd4e80f4b7e) for it by the way
